UI upgraded: only showing for ERC20-->BEP2
harmony-one/bnbridge.exchange pull request #35
Opened 2019-11-28 20:10 UTC by Renewwen

BEP2 ---> ERC20
![image](https://user-images.githubusercontent.com/49959977/69830104-fab49180-11d7-11ea-8409-6841746a8aae.png)
ERC20 ---> BEP2
![image](https://user-images.githubusercontent.com/49959977/69830110-04d69000-11d8-11ea-9512-62203a38d7b7.png)

2019-11-28 20:18 UTC, denniswon requested changes
Nit change requests.

2019-11-28 20:18 UTC, denniswon commented on bnbridge/src/components/instructions/instructions.jsx
> +
unncessary: lets remove

2019-11-28 20:18 UTC, denniswon commented on bnbridge/src/components/instructions/instructions.jsx
> +  renderBEP2_ERC20() {
breaking function naming convention: change to renderBep2ToErc20 (use lowerCamelCase)

2019-11-28 20:18 UTC, denniswon commented on bnbridge/src/components/instructions/instructions.jsx
> +  renderERC20_BEP2() {
ditto: use lowerCamelCase

2019-11-28 20:18 UTC, denniswon commented on bnbridge/src/components/instructions/instructions.jsx
> +          { swapDir === 2 && this.renderERC20_BEP2() }
define const or enum for swapDir instead of using 1, 2 hardcoded. makes code readable

2019-11-28 20:46 UTC, denniswon commented
Also, can you make the screenshot size for the memo smaller? (like 80%) just seems like the screenshot texts are as big as the websites own texts, and not clear which one is which.

2019-11-28 22:00 UTC, Renewwen commented
After changed: (the size of screenshot to 80%)
![image](https://user-images.githubusercontent.com/49959977/69833223-4c184d00-11e7-11ea-9ae3-7fe96d385dc6.png)

2019-11-29 00:30 UTC, denniswon approved these changes

2019-11-29 00:30 UTC, denniswon commented on bnbridge/src/components/instructions/instructions.jsx
> +          { swapDir === 'Bep2ToErc20' && this.renderBep2ToErc20() }
you are still hardcoding not constants or enum

2019-11-29 00:30 UTC, denniswon commented on bnbridge/src/components/instructions/instructions.jsx
> +          { swapDir === 'Bep2ToErc20' && this.renderBep2ToErc20() }
I will fix this.

2019-11-29 00:30 UTC, merged